### PR TITLE
Lore Seeker adds a booster to the draft

### PR DESCRIPTION
**Pull request by silasary**
Poking at #60

### CODE REVIEW

**Comment by jgabrielygalan** [comment]
The code looks fine. I only see a couple of things: 
- If Lore Seeker is the last pick of a pack, it won't work, cause that's handled in the autopick method.
- Lore Seeker is a "may" ability, but adding the question to the player is going to complicate everything.

**Comment by jgabrielygalan** [comment]
I think just adding the check_if_draft_matter after the pick inside autopick should be enough.

**Comment by silasary** [comment]
Yeah, I was gonna just leave the "may" for later. There's ways to do it, but it's hella messy, and we can assume people won't want to say no

**Comment by silasary** [comment]
Okay, it works, but this looks wonkey
image

**Pull request merged**
